### ISSUE TITLE
LakeFs and Minio not working

### ISSUE THREAD

**Issue by mschuch** [treeverse/lakeFS#1471]
Hi i am currently evaluation LakeFS and wanted to try it with a local MinIO installation.
But i do not get what i am doing wrong.

Here is my Docker Compose File:
```
version: '3'
services:
  lakefs:
    image: "treeverse/lakefs:${VERSION:-latest}"
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=10a718b3f285d89c36e9864494cdd1507f3bc85b342df24736ea81f9a1134bcc
      - LAKEFS_DATABASE_CONNECTION_STRING=postgres://lakefs:lakefs@postgres/postgres?sslmode=disable
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_REGION=us-east-1
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://10.10.146.217:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=minio
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_SECRET_KEY=minio123
      - LAKEFS_GATEWAYS_S3_DOMAIN_NAME=sl8-2014:8000
      - LAKEFS_GATEWAYS_S3_REGION=us-east-1
      - LAKEFS_LOGGING_LEVEL=${LAKEFS_LOGGING_LEVEL:-INFO}
      - LAKEFS_STATS_ENABLED=false
      - LAKEFS_COMMITTED_LOCAL_CACHE_DIR=${LAKEFS_COMMITTED_LOCAL_CACHE_DIR:-/home/lakefs/.local_tier}
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]
  postgres:
    image: "postgres:${PG_VERSION:-11}"
    command: "-c log_min_messages=FATAL"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
    logging:
      driver: none
```

MinIo is working and i can connect via s3Browser, with the same credentials.

Here is the error:

```
time="2021-02-17T05:56:45Z" level=error msg="bad S3 PutObject response" func="block/s3.(*Adapter).streamToS3" file="build/block/s3/adapter.go:238" error="s3 error: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>dummy</Key><BucketName>testbucket</BucketName><Resource>/testbucket/dummy</Resource><RequestId>1664735C0B686BA9</RequestId><HostId>427c0e64-fdba-477e-a460-7f97bfbd37b1</HostId></Error>" host="10.10.146.216:8000" method=POST operation=PutObject path=/api/v1/repositories request_id=3f2b3965-ac2c-4dfd-b3f2-a23fa6d573bf service_name=rest_api status_code=403 url="http://10.10.146.217:9000/testbucket/dummy" user=admin
time="2021-02-17T05:56:45Z" level=warning msg="Could not access storage namespace" func="api.(*Controller).CreateRepositoryHandler.func1" file="build/api/controller.go:544" error="s3 error: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>dummy</Key><BucketName>testbucket</BucketName><Resource>/testbucket/dummy</Resource><RequestId>1664735C0B686BA9</RequestId><HostId>427c0e64-fdba-477e-a460-7f97bfbd37b1</HostId></Error>" service=api_gateway storage_namespace="s3://testbucket/"

```

Where is my Problem? Thanks in advance

**Comment by johnnyaug** [comment]
Hey @mschuch, thank you for opening this issue. I wasn't able to reproduce it using the same docker-compose.yml.
Could you share with me which version of minio you are using, and how you are running it?

**Comment by mschuch** [comment]
This is the docker compose file i use to start minio:
```
version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2021-02-14T04-01-33Z
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```
