### ISSUE TITLE
Failed to parse response using boto3 when using docker compose

### ISSUE THREAD

**Issue by gangtao** [treeverse/lakeFS#1574]
I started the lakefs using docker and the try to run some sample code with boto3 as following.
```

version: '3'
services:
  lakefs:
    image: "treeverse/lakefs:${VERSION:-latest}"
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY:-some random secret string}
      - LAKEFS_DATABASE_CONNECTION_STRING=${LAKEFS_DATABASE_CONNECTION_STRING:-postgres://lakefs:lakefs@postgres/postgres?sslmode=disable}
      - LAKEFS_BLOCKSTORE_TYPE=${LAKEFS_BLOCKSTORE_TYPE:-local}
      - LAKEFS_BLOCKSTORE_LOCAL_PATH=${LAKEFS_BLOCKSTORE_LOCAL_PATH:-/home/lakefs}
      - LAKEFS_GATEWAYS_S3_DOMAIN_NAME=${LAKEFS_GATEWAYS_S3_DOMAIN_NAME:-s3.local.lakefs.io:8000}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - LAKEFS_LOGGING_LEVEL=${LAKEFS_LOGGING_LEVEL:-INFO}
      - LAKEFS_STATS_ENABLED
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE
      - LAKEFS_CATALOGER_TYPE
      - LAKEFS_COMMITTED_LOCAL_CACHE_DIR=${LAKEFS_COMMITTED_LOCAL_CACHE_DIR:-/home/lakefs/.local_tier}
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]
  postgres:
    image: "postgres:${PG_VERSION:-11}"
    command: "-c log_min_messages=FATAL"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
    logging:
      driver: none

```

```
import boto3
s3 = boto3.client('s3',
    endpoint_url='http://host.docker.internal:8000',
    aws_access_key_id='myid',
    aws_secret_access_key='mykey',
                 use_ssl=False)

with open('./test.txt', 'rb') as f:
    s3.put_object(Body=f, Bucket='test', Key='text.txt')
```

it returns following error
```
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _parse_xml_string_to_dom(self, xml_string)
    450                 encoding=self.DEFAULT_ENCODING)
--> 451             parser.feed(xml_string)
    452             root = parser.close()

ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

ResponseParserError                       Traceback (most recent call last)
<ipython-input-38-276b5769cb6a> in <module>
      1 with open('./test.txt', 'rb') as f:
----> 2     s3.put_object(Body=f, Bucket='test', Key='text.txt')

/opt/conda/lib/python3.8/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

/opt/conda/lib/python3.8/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    660             http, parsed_response = event_response
    661         else:
--> 662             http, parsed_response = self._make_request(
    663                 operation_model, request_dict, request_context)
    664 

/opt/conda/lib/python3.8/site-packages/botocore/client.py in _make_request(self, operation_model, request_dict, request_context)
    680     def _make_request(self, operation_model, request_dict, request_context):
    681         try:
--> 682             return self._endpoint.make_request(operation_model, request_dict)
    683         except Exception as e:
    684             self.meta.events.emit(

/opt/conda/lib/python3.8/site-packages/botocore/endpoint.py in make_request(self, operation_model, request_dict)
    100         logger.debug("Making request for %s with params: %s",
    101                      operation_model, request_dict)
--> 102         return self._send_request(request_dict, operation_model)
    103 
    104     def create_request(self, params, operation_model=None):

/opt/conda/lib/python3.8/site-packages/botocore/endpoint.py in _send_request(self, request_dict, operation_model)
    132         request = self.create_request(request_dict, operation_model)
    133         context = request_dict['context']
--> 134         success_response, exception = self._get_response(
    135             request, operation_model, context)
    136         while self._needs_retry(attempts, operation_model, request_dict,

/opt/conda/lib/python3.8/site-packages/botocore/endpoint.py in _get_response(self, request, operation_model, context)
    164         # If an exception occurs then the success_response is None.
    165         # If no exception occurs then exception is None.
--> 166         success_response, exception = self._do_get_response(
    167             request, operation_model)
    168         kwargs_to_emit = {

/opt/conda/lib/python3.8/site-packages/botocore/endpoint.py in _do_get_response(self, request, operation_model)
    215         protocol = operation_model.metadata['protocol']
    216         parser = self._response_parser_factory.create_parser(protocol)
--> 217         parsed_response = parser.parse(
    218             response_dict, operation_model.output_shape)
    219         # Do a second parsing pass to pick up on any modeled error fields

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in parse(self, response, shape)
    243                 parsed = self._do_error_parse(response, shape)
    244         else:
--> 245             parsed = self._do_parse(response, shape)
    246 
    247         # We don't want to decorate event stream responses with metadata

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _do_parse(self, response, shape)
    807         final_parsed['ResponseMetadata'] = self._populate_response_metadata(
    808             response)
--> 809         self._add_modeled_parse(response, shape, final_parsed)
    810         return final_parsed
    811 

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _add_modeled_parse(self, response, shape, final_parsed)
    816         self._parse_non_payload_attrs(response, shape,
    817                                       member_shapes, final_parsed)
--> 818         self._parse_payload(response, shape, member_shapes, final_parsed)
    819 
    820     def _do_modeled_error_parse(self, response, shape):

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _parse_payload(self, response, shape, member_shapes, final_parsed)
    856                     body_shape, original_parsed)
    857         else:
--> 858             original_parsed = self._initial_body_parse(response['body'])
    859             body_parsed = self._parse_shape(shape, original_parsed)
    860             final_parsed.update(body_parsed)

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _initial_body_parse(self, xml_string)
    942         if not xml_string:
    943             return ETree.Element('')
--> 944         return self._parse_xml_string_to_dom(xml_string)
    945 
    946     def _do_error_parse(self, response, shape):

/opt/conda/lib/python3.8/site-packages/botocore/parsers.py in _parse_xml_string_to_dom(self, xml_string)
    452             root = parser.close()
    453         except XMLParseError as e:
--> 454             raise ResponseParserError(
    455                 "Unable to parse response (%s), "
    456                 "invalid XML received. Further retries may succeed:\n%s" %

ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>lakeFS App</title><link href="/static/css/2.9148c9c3.chunk.css" rel="stylesheet"><link href="/static/css/main.8b3c9760.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,i,l=r[0],f=r[1],a=r[2],c=0,s=[];c<l.length;c++)i=l[c],Object.prototype.hasOwnProperty.call(o,i)&&o[i]&&s.push(o[i][0]),o[i]=0;for(n in f)Object.prototype.hasOwnProperty.call(f,n)&&(e[n]=f[n]);for(p&&p(r);s.length;)s.shift()();return u.push.apply(u,a||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,l=1;l<t.length;l++){var f=t[l];0!==o[f]&&(n=!1)}n&&(u.splice(r--,1),e=i(i.s=t[0]))}return e}var n={},o={1:0},u=[];function i(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}i.m=e,i.c=n,i.d=function(e,r,t){i.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},i.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},i.t=function(e,r){if(1&r&&(e=i(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(i.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)i.d(t,n,function(r){return e[r]}.bind(null,n));return t},i.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(r,"a",r),r},i.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},i.p="/";var l=this.webpackJsonpwebui=this.webpackJsonpwebui||[],f=l.push.bind(l);l.push=r,l=l.slice();for(var a=0;a<l.length;a++)r(l[a]);var p=f;t()}([])</script><script src="/static/js/2.2a18957f.chunk.js"></script><script src="/static/js/main.e39742f0.chunk.js"></script></body></html>'
```

did I use the wrong end point , what should be the right one to use?
