### ISSUE TITLE
cannot connect to S3 (Min.io) :  "NoCredentialProviders: no valid providers in chain. Deprecated"

### ISSUE THREAD

**Issue by marioramaglia** [treeverse/lakeFS#1728]
Hi there all, 
lakeFS 0.33.1 has been configured (configuration attached below) to connect to a local Min.io process running on http port 9000.

- All is installed on prem , no containers;
- minio version: RELEASE.2021-03-01T04-20-55Z
- lakeFS version: 0.33.1  (https://github.com/treeverse/lakeFS/releases/download/v0.33.1/lakeFS_0.33.1_Linux_x86_64.tar.gz)
- os: RHEL 7.6

**lakeFS throws the following warning during startup:**
```

_WARNING[2021-04-06T19:08:56+02:00]lakeFS/pkg/logging/logger.go:119 pkg/logging.(*logrusEntryWrapper).Warnf NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors: failed to get AWS account ID for BI_
```

log capturing the  process start:
[run.log](https://github.com/treeverse/lakeFS/files/6266908/run.log)

**When trying to create a new repository via the UI the same error is thrown in the log:**

```
ERROR  [2021-04-06T20:09:34+02:00]lakeFS/pkg/block/s3/adapter.go:174 pkg/block/s3.(*Adapter).streamToS3 failed to sign request                        error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" host="10.204.31.53:8000" method=POST operation=PutObject path=/api/v1/repositories request_id=0c8faf9f-afe9-4f60-8b90-8ca9c4947ca9 service_name=rest_api user=admin
WARNING[2021-04-06T20:09:34+02:00]lakeFS/pkg/api/controller.go:567 pkg/api.(*Controller).CreateRepositoryHandler.func1 Could not access storage namespace            error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" service=api_gateway storage_namespace="s3://datalake/"
```

![ui_create_repo](https://user-images.githubusercontent.com/82051970/113761456-c3cd8480-9717-11eb-84ed-39d92b6065ea.gif)

**Here you have the relevant s3 config (see lakefs.yaml  attached);  
tried both static and file based credentials properties:**

...
```
s3:
    region: us-east-1
    force_path_style: true
    endpoint: https://localhost:9000
    credentials:
      #access_key_id: admin
      #access_secret_key: Intesa01
      credentials_file: /cvai0/sw/lakefs_0.33.1/aws_credentials
```
...

lakefs.yaml:
[lakefs.txt](https://github.com/treeverse/lakeFS/files/6266898/lakefs.txt)

aws_credentials file:
[aws_credentials.txt](https://github.com/treeverse/lakeFS/files/6266825/aws_credentials.txt)

**BTW: when trying to connect to Minio with another s3 client (eg s3cmd) all is working smoothless, ie:**
`s3cmd -c s3cfg ls s3://datalake/`

s3cfg:
```
# Setup endpoint
host_base = localhost:9000
host_bucket = localhost:9000
bucket_location = us-east-1
use_https = False

# Setup access keys
access_key = admin
secret_key = Intesa01

# Enable S3 v4 signature APIs
signature_v2 = False

```

best regards,
thanks
Mario Ramaglia

**Comment by arielshaqed** [comment]
Thanks for the detailed report!

I am a bit confused about another part of the `s3` stanza:

```yaml
s3:
    region: us-east-1
    force_path_style: true
    endpoint: https://localhost:9000
    credentials:
      #access_key_id: admin
      #access_secret_key: Intesa01
      credentials_file: /cvai0/sw/lakefs_0.33.1/aws_credentials
```

The S3 endpoint is `https://localhost:9000`.  I am not sure how lakeFS would agree to accept a certificate for `localhost`.  Could you try to connect on loopback over http?
