### ISSUE TITLE
Airflow Hook: panic assignment to entry in nil map

### ISSUE THREAD

**Issue by kipliko** [treeverse/lakeFS#2533]
Hi,
I'm testing an Airflow hook locally but when I merge from branch I get the following error:

```
**panic: assignment to entry in nil map**

goroutine 623 [running]: github.com/treeverse/lakefs/pkg/actions.(*Airflow).Run(0xc00aacb0...)
	/build/pkg/actions/airflow.go:93 +0x128
github.com/treeverse/lakefs/pkg/actions.(*Service).runTasks.func1(0x28d01c0, 0x1e72f98)
	/build/pkg/actions/service.go:197 +0x325
github.com/hashicorp/go-multierror.(*Group).Go.func1(0xc00ac9e7a0, 0xc00aca8bc0)
	/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:23 +0x5c
created by github.com/hashicorp/go-multierror.(*Group).Go
	/go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/group.go:20 +0x66
```

### **How to reproduce the error**

My hook file uploaded under _lakefs_actions/ of the main branch.

```yml
name: Good files check
description: set of checks to verify that branch is good
on:
  pre-commit:
  pre-merge:
    branches:
      - main
hooks:
  - id: trigger_my_dag
    type: airflow
    description: Trigger an example_dag
    properties:
       url: "http://airflow-poc-web:8080"
       dag_id: "k8s_test_dag"
       username: "****"
       password: "****"
```

When I try to merge from the test branch to master I get the error.

**Comment by itaiad200** [comment]
Hey @kipliko - Thanks for opening the issue, I was able to reproduce it locally.
In some cases, the additional properties map is lacking initialization and that what causes the panic. PR #2534 has the fix, but I still need to add tests and then release a version. 

Meanwhile there's a quick detour you can take that will unblock you for now. Just need to add some dummy properties to your yaml file, such as:

```yml
name: Good files check
description: set of checks to verify that branch is good
on:
  pre-commit:
  pre-merge:
    branches:
      - main
hooks:
  - id: trigger_my_dag
    type: airflow
    description: Trigger an example_dag
    properties:
       url: "http://airflow-poc-web:8080"
       dag_id: "k8s_test_dag"
       username: "****"
       password: "****"
       dag_conf:
          some: "additional_conf"
```

Let us know if that did the trick for now.
