### ISSUE TITLE
Make Trino Client in Bagel Connectable to DBeaver

### ISSUE THREAD

**Issue by peacing** [treeverse/lakeFS#2807]
Hi,

It is useful to be able to connect to the Trino instance in the Everything Bagel with a Database UI like Dbeaver. The only way I've found to be able to do this (as done in the EB Part II blog) is to comment out the trino-client service and expose port 8080 on the trino service like so:

```
trino:
    image: trinodb/trino:358
    container_name: trino
    volumes:
      - ./etc/s3.properties:/etc/trino/catalog/s3.properties
    ports:
      - 8080:8080

  # trino-client:
  #   image: trinodb/trino:358
  #   profiles: ["client"]
  #   entrypoint: ["trino", "--server", "trino:8080", "--catalog", "s3", "--schema", "default"]
```

Is there a way to enable this functionality within the trino-client service? I tried a few things like exposing port 8080 on the trino-client service and changing the port exposing on the trino service to be 8080:8080 instead of 8080:48080 but queries run in dbeaver when connected to 0.0.0.0:8080 or 0.0.0.0:48080 still did not work.

Thoughts?

**Comment by guy-har** [comment]
@peacing there are two options:
- map Trino port to your local machine and connect Dbeaver using the port you mapped. (exactly like you did)
- Add another container for Dbeaver and you will have access to the Trino machine in the docker-compose (using `tino:8080`)

According to `8080:48080`, it's a bug and should be `48080:48080` fixed in #2818

**Comment by peacing** [comment]
@guy-har What does the change from 8080:48080 to 48080:8080 do? We still need to make another change to connect via dbeaver, yes?

**Comment by guy-har** [comment]
@peacing, the change is a bug fix. you could now connect to Trino via `localhost:48080`.  We still have the two options mentioned above in order to connect to trino.
- Connect dbeaver from the machine running docker-compose using the address `localhost:48080`
- Add dbeaver to docker compose and use the address `trino:8080`

If we would like to work with the second option, you should:
1. edit the `docker-compose.yaml` file by adding 
```
  dbeaver:
    image: dbeaver/cloudbeaver
    profiles: ["client"]
    ports:
      - "8978:8978"

```

2. run `docker-compose up -d`
3. run `docker-compose up -d dbeaver`
4. browse to `http://localhost:8978/`
5. in database connections -> Add Database -> custom , choose trino
6. use `trino` as host, and choose any User Name ( do not user password, it is not supported)
![Screen Shot 2021-12-21 at 18 29 39](https://user-images.githubusercontent.com/60321938/146964896-5eaa7d4e-0abd-4d5e-90e1-c6f07c0e65de.png)
