### ISSUE TITLE
Use assumed roles in GitHub actions

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2953]
In many of our GitHub workflows, we use this step:
```
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
```
Instead of using secret keys, use assumed roles. 

I made an attempt to achieve this in 5db78fce, but couldn't get all the tests to pass and eventually gave up. You can start from this commit and debug.
