### ISSUE TITLE
Glue catalog_id parsed as int

### ISSUE THREAD

**Issue by phzietsman** [treeverse/lakeFS#2996]
When specifying a Glue catalog id in the config file, the value is read as an integer. In cases where the account id has a leading zero all arns generated for resources in the account will be incorrect. Either the docs need to be updated to specify that the account id / catalog id should be quoted or the parser needs a look.

```
metastore:
  type: glue
  glue:
    catalog-id: 023456789012
```

should be 

```
metastore:
  type: glue
  glue:
    catalog-id: "023456789012"
```
