### ISSUE TITLE
Required jobs are not running on documentation changes and block merge

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3350]
When performing documentation changes, the required jobs: "Run Linters and Checkers" "Run Go tests" are skipped due to workflow configuration:
```
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "design/**"
```
Since these jobs are required for merge, merge is blocked.
The problem is, it's currently not possible to mark jobs as not required only for a specific path. Need to find a way to work around it
