### ISSUE TITLE
Content-Length HTTP header

### ISSUE THREAD

**Issue by gotjoshua** [treeverse/lakeFS#3582]
I am trying to connect to StorJ S3 endpoint (which is working fine with filestash) but the repo creation fails.

 i get this error:

```json
"error": "s3 error: 
<xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error>
    <Code>
    MissingContentLength</Code>
    <Message>
    You must provide the Content-Length HTTP header.</Message>
    <Key>
    dummy</Key>
    <BucketName>
    lakefs</BucketName>
    <Resource>
    /lakefs/dummy</Resource>
    <RequestId>
    16FCB8279798AF4B</RequestId>
    <HostId>
    </HostId>
</Error>
",
"file":"build/pkg/block/s3/adapter.go:250",
"func":"pkg/block/s3.(*Adapter).streamToS3",
"host":"lakefs.1zm.in",
"level":"error",
"log_audit":"API",
"method":"POST",
"msg":"bad S3 PutObject response",
"operation":"PutObject",
"path":"/api/v1/repositories",
"request_id":"db65f373-c188-414c-8b69-f8c1096bb5ed",
"service_name":"rest_api",
"status_code":411,
"time":"2022-06-28T07:27:23Z",
"url":"https://gateway.storjshare.io/lakefs/dummy"
}
```

config.yml
```yml
---
logging:
  format: json
  level: TRACE
  output: "-"

database:
  connection_string: "postgres://lakefs:lakefs@postgres/postgres?sslmode=disable"

auth:
  encrypt:
    secret_key: "12 word phrase"

blockstore:
  type: s3
  default_namespace_prefix: "s3://"
  s3:
    force_path_style: true
    endpoint: "https://gateway.storjshare.io"
    discover_bucket_region: false
    credentials:
      access_key_id: key
      secret_access_key: secret
```

any ideas?
