### ISSUE TITLE
Cannot reproduce benchmark performance in document

### ISSUE THREAD

**Issue by WarBean** [treeverse/lakeFS#3946]
According to [this](https://docs.lakefs.io/understand/sizing-guide.html#random-writes):

> So, 50% of all requests took <10ms, while 99.9% of them took <25ms.
> 
> throughput:
> 
> The average throughput during the experiment was 7595.46 requests/second.

My results with `--parallelism 64`:

```
$ lakectl abuse random-write --amount 10000 --parallelism 64 lakefs://test/main
Source branch: lakefs://test/main
stage object - completed: 400, errors: 0, current rate: 338.11 done/second
stage object - completed: 887, errors: 0, current rate: 487.15 done/second
stage object - completed: 1390, errors: 0, current rate: 502.92 done/second
stage object - completed: 1889, errors: 0, current rate: 499.26 done/second
stage object - completed: 2377, errors: 0, current rate: 488.08 done/second
stage object - completed: 2850, errors: 0, current rate: 472.81 done/second
stage object - completed: 3341, errors: 0, current rate: 490.99 done/second
stage object - completed: 3806, errors: 0, current rate: 465.30 done/second
stage object - completed: 4299, errors: 0, current rate: 492.98 done/second
stage object - completed: 4808, errors: 0, current rate: 508.84 done/second
stage object - completed: 5306, errors: 0, current rate: 497.78 done/second
stage object - completed: 5813, errors: 0, current rate: 507.01 done/second
stage object - completed: 6321, errors: 0, current rate: 508.44 done/second
stage object - completed: 6828, errors: 0, current rate: 507.01 done/second
stage object - completed: 7317, errors: 0, current rate: 488.78 done/second
stage object - completed: 7804, errors: 0, current rate: 487.28 done/second
stage object - completed: 8258, errors: 0, current rate: 453.88 done/second
stage object - completed: 8616, errors: 0, current rate: 357.88 done/second
stage object - completed: 8923, errors: 0, current rate: 307.09 done/second
stage object - completed: 9341, errors: 15, current rate: 417.96 done/second
stage object - completed: 9811, errors: 20, current rate: 470.03 done/second
completed: 10000, errors: 20, current rate: 514.52 done/second

Histogram (ms):
1       0
2       0
5       0
7       0
10      0
15      0
25      0
50      0
75      0
100     0
250     9962
350     9973
500     9974
750     9978
1000    9978
5000    9980
min     106
max     1572
total   9980
```

with `--parallelism 1`:

```
$ lakectl abuse random-write --amount 100 --parallelism 1 lakefs://test/main
Source branch: lakefs://test/main
stage object - completed: 0, errors: 0, current rate: 0.00 done/second
stage object - completed: 0, errors: 0, current rate: 0.00 done/second
stage object - completed: 0, errors: 0, current rate: 0.00 done/second
stage object - completed: 0, errors: 0, current rate: 0.00 done/second
stage object - completed: 0, errors: 0, current rate: 0.00 done/second
stage object - completed: 7, errors: 0, current rate: 7.00 done/second
stage object - completed: 15, errors: 0, current rate: 8.00 done/second
stage object - completed: 22, errors: 0, current rate: 7.00 done/second
stage object - completed: 29, errors: 0, current rate: 6.99 done/second
stage object - completed: 37, errors: 0, current rate: 8.00 done/second
stage object - completed: 45, errors: 0, current rate: 8.00 done/second
stage object - completed: 53, errors: 0, current rate: 8.01 done/second
stage object - completed: 61, errors: 0, current rate: 7.99 done/second
stage object - completed: 68, errors: 0, current rate: 7.00 done/second
stage object - completed: 75, errors: 0, current rate: 7.00 done/second
stage object - completed: 83, errors: 0, current rate: 8.00 done/second
stage object - completed: 91, errors: 0, current rate: 8.00 done/second
stage object - completed: 99, errors: 0, current rate: 8.00 done/second
completed: 100, errors: 0, current rate: 14.53 done/second

Histogram (ms):
1       0
2       0
5       0
7       0
10      0
15      0
25      0
50      0
75      0
100     0
250     99
350     99
500     99
750     99
1000    99
5000    99
min     118
max     5165
total   100
```

My docker-compose configuration (note that I use local blockstore):

```
version: '3'
services:
    lakefs:
        image: "treeverse/lakefs:${VERSION:-latest}"
        ports:
            - "12300:8000"
        depends_on:
            - "postgres"
        environment:
            - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY:-some random secret string}
            - LAKEFS_DATABASE_CONNECTION_STRING=${LAKEFS_DATABASE_CONNECTION_STRING:-postgres://lakefs:lakefs@postgres/postgres?sslmode=disable}
            - LAKEFS_DATABASE_MAX_OPEN_CONNECTIONS=${LAKEFS_DATABASE_MAX_OPEN_CONNECTIONS:-1000}
            - LAKEFS_DATABASE_MAX_IDLE_CONNECTIONS=${LAKEFS_DATABASE_MAX_IDLE_CONNECTIONS:-1000}
            - LAKEFS_BLOCKSTORE_TYPE=${LAKEFS_BLOCKSTORE_TYPE:-local}
            - LAKEFS_BLOCKSTORE_LOCAL_PATH=${LAKEFS_BLOCKSTORE_LOCAL_PATH:-/home/lakefs}
            - LAKEFS_GATEWAYS_S3_DOMAIN_NAME=${LAKEFS_GATEWAYS_S3_DOMAIN_NAME:-s3.local.lakefs.io:8000}
            - LAKEFS_LOGGING_LEVEL=${LAKEFS_LOGGING_LEVEL:-INFO}
            - LAKEFS_STATS_ENABLED
            - LAKEFS_BLOCKSTORE_S3_ENDPOINT
            - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE
            - LAKEFS_COMMITTED_LOCAL_CACHE_DIR=${LAKEFS_COMMITTED_LOCAL_CACHE_DIR:-/home/lakefs/.local_tier}
        entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]
        volumes:
            - /data/zhenghuabin/lakefs_storage:/home/lakefs:rw
    postgres:
        image: "postgres:${PG_VERSION:-11}"
        ports:
            - "12301:5432"
        command: "-c log_min_messages=FATAL"
        environment:
            POSTGRES_USER: lakefs
            POSTGRES_PASSWORD: lakefs
            PGDATA: /home/postgres
        logging:
            driver: none
        volumes:
            - /data/zhenghuabin/postgres_storage:/home/postgres:rw
            - ./postgresql.conf:/home/postgres/postgresql.conf:rw
```

Besides, I already set `max_connections = 1000` and `shared_buffer = 1024MB` in PostgreSQL configuration.

Wondering why I cannot reproduce the same write performance as official documents. Can anyone help?
