### ISSUE TITLE
Pagination API incorrect with amount==1 and a prefix that matches

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4356]
This is particularly relevant for auth.  When:

* A List* operation is called with a prefix; and
* that prefix (also) exactly matches an element; and
* amount is set to 1

then pagination is impossible.

 The API provides these pagination parameters:

``` yaml
    Pagination:
      type: object
      required:
        - has_more
        - max_per_page
        - results
        - next_offset
      properties:
        has_more:
          type: boolean
          description: Next page is available
        next_offset:
          type: string
          description: Token used to retrieve the next page
        results:
          type: integer
          minimum: 0
          description: Number of values found in the results
        max_per_page:
          type: integer
          minimum: 0
          description: Maximal number of entries per page
```

The way pagination works is that after you get a response with
`has_more==true` and `next_offset` set to the key of the last element.  Now
you can call again with `after` set to `next_offset` -- which starts
returning elements _after_ `next_offset`, so continues the listing.

Unfortunately, a non-empty `after` parameter means _strictly_ after that
provided key, but an empty `after` parameter is ignored -- it behaves as _at
or after_ that provided (empty) key, and will return such a key.

Suppose we search with amount==1 and the prefix matches.  Then that _is_ the
first element.  So the first response _should_ include `has_more==true`[^1],
but `next_offset==""` will be the empty string.  So the next call *also*
sends `after=""`.  Now we call with the same prefix and `after==""`.  But
that means "ignore after", so we get the same result again -- and an
infinite loop.

I do not understand how this API can work, unfortunately.

[^1]: In practice even _that_ does not happen, as the internal API used in
    KV auth has similar issues!
