### ISSUE TITLE
Configurable database pool parameters

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#443]

**Comment by nopcoder** [comment]
Configurable database connection parameters:
```yaml
database:
  max_open_connections: 25
  max_idle_connections: 25
  connection_max_lifetime: 5m
```
