### ISSUE TITLE
Running lakefs with configured local database creates ~ on working directory

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#4565]
Running lakeFS configured using local database, using empty 'local' scope:

```yaml
database:
  type: local
  local:
```

While running lakeFS, a directory "~/metadata" is created under the current working folder. (Note that "~" is not expanded to evaluated as home directory)
