### ISSUE TITLE
No repositories after restart and issues creating repository on existing S3 bucket

### ISSUE THREAD

**Issue by FredrikBakken** [treeverse/lakeFS#6256]
### What happened?

**Current Behavior:**
Creating repository on already existing S3 storage results in the following error message:
```sh
failed to create repository: found lakeFS objects in the storage namespace(s3://test): storage namespace already in use
```
        
**Steps to Reproduce:**
1. Create a `docker-compose.yml` file with the following contents:
   ```
   version: '3.9'
   
   services:
     minio:
       image: minio/minio:RELEASE.2023-06-29T05-12-28Z
       container_name: minio
       ports:
         - "9000:9000"
         - "9001:9001"
       entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]
  
     postgres:
       image: postgres:14
       container_name: postgres
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
       healthcheck:
         test: ["CMD", "pg_isready", "-U", "postgres"]
         interval: 10s
         retries: 5
         start_period: 5s
       restart: always

     minio-setup:
       image: minio/mc:RELEASE.2023-06-28T21-54-17Z
       container_name: minio-setup
       environment:
           - MC_HOST_lakefs=http://minioadmin:minioadmin@minio:9000
       depends_on:
         - minio
       entrypoint: >
         /bin/sh -c "
         /usr/bin/mc mb lakefs/test;
         exit 0;
         "

     lakefs:
       image: treeverse/lakefs:0.104.0
       container_name: lakefs
       depends_on:
         - postgres
         - minio-setup
       ports:
         - "8000:8000"
       environment:
         - LAKEFS_DATABASE_TYPE=local
         - LAKEFS_BLOCKSTORE_TYPE=s3
         - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
         - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
         - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=minioadmin
         - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=minioadmin
         - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
         - LAKEFS_STATS_ENABLED
         - LAKEFS_LOGGING_LEVEL
         - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
         - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
         - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
         - LAKEFS_DATABASE_CONNECTION_STRING=postgres://postgres:postgres@postgres-lakefs/postgres?sslmode=disable
       entrypoint: ["/bin/sh", "-c"]
       command:
           - |
             lakefs setup --local-settings --user-name docker --access-key-id AKIAIOSFODNN7EXAMPLE --secret-access-key wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY || true
             lakefs run --local-settings &
             wait-for -t 60 lakefs:8000 -- lakectl repo create lakefs://test s3://test || true
             wait
   ```
3. Start this docker container environment by running: `docker compose up`
4. Go to the `test` repository in the UI on http://localhost:8000 and upload a file, e.g. `test.txt`
5. Simulate a restart of LakeFS by running the following two commands in the terminal:
   ```sh
   docker compose down lakefs
   docker compose up
   ```
7. Now open the LakeFS UI again, where you now can see that no repositories are found
8. Try to re-create repository in the UI by creating an empty repository with the following details:
   - **Repository ID**: test
   - **Storage Namespace**: s3://test
   - **Default Branch**: main

### Expected Behavior

**Expected Behavior:**

Expecting behavior is that after a restart of LakeFS, the repositories are still visible in the UI. If they do not show up, make it possible to create repository on existing S3 storage.

Using the import functionality does not seem to satisfy the requirements as the files are of binary format that does not have the same naming scheme as previously uploaded.

### lakeFS Version

0.104.0

### Deplyoment

Local with min.io, and Azure Container Instance with blob storage
