### ISSUE TITLE
Question: How to create local lakeFS instances with `S3` as storage adapter?

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#6579]
Hello again,

I am looking to implement pre-signed URL support for the `lakefs-spec` project (https://github.com/appliedAI-Initiative/lakefs-spec). After a first attempt, I get the client error response saying that pre-signed URLs are not supported for the local storage adapter, which makes perfect sense.

The question is now: How do I prepare a local lakeFS instance with the S3 storage adapter? Looking at the lakeFS service diagram, I suspect this will not be as easy as switching the block store type in the config.

**Comment by idanovo** [comment]
Hi @nicholasjng,

Thanks for your question.
Running lakeFS local with S3 shouldn't be a problem at all.
You can use this lakefs.yaml configuration example:
```
----
logging:
  format: json
  level: TRACE
  output: "-"

database:
  type: "local"
auth:
  encrypt:
    secret_key: <random-secret-key>

blockstore:
  type: s3
  s3:
      region: us-east-1
---
```

You should be logged in with an AWS profile with proper credentials when you run your lakeFS profile.
Please let me know if you managed to work it out or if you need any help

**Comment by nicholasjng** [comment]
Thank you for the response! Is there a way to run a setup like this within a single Docker image similarly to the lakeFS quickstart?

**Comment by idanovo** [comment]
Sure.

You can run lakeFS [image](https://hub.docker.com/r/treeverse/lakefs) using docker by:

1. Run the docker run command and pass configurations as environment variables
e.g.- `docker run --name lakefs  --rm --publish 8000:8000 -e LAKEFS_DATABASE_TYPE='local' .... treeverse/lakefs:latest  run`
2. Use a docker-compose file that will look like this more or less:
```
version: '3'
services:
  lakefs:
    image: "treeverse/lakefs:latest"
    command: "run"
    ports:
      - "8000:8000"
    volumes:
      - lakefs-app:/app:ro
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_DATABASE_TYPE=local
    entrypoint: ["/app/lakefs", "run"]
```
