### ISSUE TITLE
[Bug]: Local kvstore returns error and exits (M1 Mac)

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6729]
### What happened?

From Slack:

Running the LakeFS image locally via docker-compose for being able to do dev work on our laptops, connected to a local minio instance. Running into a weird issue on my M1 Mac. First time I run the docker-compose everything works fine. Then, after I quit, verify there are no still running containers with docker ps, and re-run our docker-compose, the LakeFS image consistently throws one of two errors and exits:
```
Failed to setup DB: failed to open KV store: while opening memtables error: while opening fid: 1 error: while updating skiplist error: mremap size mismatch: requested: 740 got: 134217728
```
or
```
Failed to setup DB: failed to open KV store: During db.vlog.open error: while truncating last value log file: /home/lakefs/lakefs/metadata/000003.vlog error: mremap size mismatch: requested: 20 got: 2147483646
```
After stopping the docker-compose, running docker ps -a and deleting the already exited LakeFS container with docker rm, and re-running docker-compose, it works fine again on the first try, until I stop it and the cycle starts anew. Sounds like an ARM issue to me but I'm not sure. My local Docker Desktop is up to date and has plenty of resources.
I have a workaround so it's non-blocking, but I didn't see the issue mentioned anywhere on GitHub so I thought you should know. I can create an Issue if you think it best. docker-compose YAML is as follows:
```
  lakefs:
    platform: linux/arm64  # Specify the desired platform architecture
    image: docker-remote.artifactory-ha.tmc-stargate.com/treeverse/lakefs:0.111.1
    entrypoint: /init/startup_lakefs.sh
    ports:
      - 8000:8000 # make it accessible from K8s Pods using internal host
    env_file: ./config/.env.lakefs
    depends_on:
      minio:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    volumes:
    - type: bind
      source: ./startup_script
      target: /init
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "http://localhost:8000/_health"
        ]
```

Still getting the error after using volumes with docker-compose. Not sure why.

```
# .env.lakefs
LAKEFS_DATABASE_LOCAL_PATH=/app/database
```

```
  lakefs:
    user: root
    platform: linux/arm64  # Specify the desired platform architecture
    image: docker-remote.artifactory-ha.tmc-stargate.com/treeverse/lakefs:0.111.1
    entrypoint: /init/startup_lakefs.sh
    ports:
      - 8000:8000 # make it accessible from K8s Pods using internal host
    env_file: ./config/.env.lakefs
    depends_on:
      minio:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    volumes:
    - type: volume
      source: lakefs-data
      target: /app/database
    - type: bind
      source: ./startup_script
      target: /init
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "http://localhost:8000/_health"
        ]

volumes:
  minio-data:
  lakefs-data:
```
