### ISSUE TITLE
[Bug]: Error uploading Parquet file larger than 7MB: s3 error: missing ETag

### ISSUE THREAD

**Issue by Youssef-Harby** [treeverse/lakeFS#6736]
### What happened?

I have encountered an issue while trying to upload Parquet files larger than ~7MB or over a certain duration using the LakeFS UI. The issue seems to arise particularly when uploading a file larger than 10MB from a specific source. When I attempt the upload, I receive an error message in the UI, and no logs are generated for further insight.
Steps to Reproduce:

1. Run docker-compose up to start LakeFS.
2. Create a new repository.
3. Attempt to upload a file larger than 10MB from the following source: https://beta.source.coop/cholmes/overture/places-geoparquet-country

The UI displays the error message: s3 error: missing ETag, and no logs are generated for debugging.
![image](https://github.com/treeverse/lakeFS/assets/13020265/59b3572b-2e4a-41ba-889d-30dfaea5b6a8)

Additional Information:
- I am using contabo object storage and enabled all CORS and ETag …etc. with AWS CLI
- I suspect the issue may be related to either the file size or the duration of the upload, but I am not entirely certain about the exact cause.
- There is no additional log information available to provide more context on this error.
- The issue persists regardless of the browser used.

the docker-compose.yml :
```yaml
version: '3.8'  # updated to version 3.4 to use healthcheck condition in depends_on
services:
  lakefs:
    image: yharby/lakefs:latest
    container_name: lakefs
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://secret:secret@postgres:5432/secret
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=ca7a41c47b06bf3762af3df69e2a98d5847a6e22c7b85d6f17e5801e3397040e9f6306ed8c10b5ccd02723caa0b2fe67071fbb9b86c4702b3a872ab9444b1806
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=https://eu2.contabostorage.com
      - LAKEFS_BLOCKSTORE_S3_DISCOVER_BUCKET_REGION=false
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=secret
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=secret
      - LAKEFS_GRAVELER_REPOSIORY_CACHE_TTL=1h
      - LAKEFS_GRAVELER_REPOSIORY_CACHE_SIZE=9999999999
      - LAKEFS_AUTH_CACHE_JITTER=1h
      - LAKEFS_AUTH_REMOTE_AUTHENTICATOR_REQUEST_TIMEOUT=20m
      - LAKEFS_STATS_ENABLED
      - LAKEFS_AUTH_CACHE_TTL=20m
      - LAKEFS_GRAVELER_COMMIT_CACHE_JITTER=1h
      - LAKEFS_GRAVELER_COMMIT_CACHE_TTL=1h
    depends_on:
      postgres:
        condition: service_healthy  # depends on postgres being healthy
    command: run

  postgres:
    image: kartoza/postgis:15-3.4
    container_name: postgres
    environment:
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:  # healthcheck directive
      test: "PGPASSWORD=secret pg_isready -h 127.0.0.1 -U secret -d secret"
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
```

### Expected behavior

The file should be uploaded successfully to the newly created repository.

### lakeFS version

v0.112.1 / latest

### How lakeFS is installed

Docker

### Contact details

me@youssefharby.com
