### ISSUE TITLE
Limit LogCommits lookback period

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#6814]
Logging the commits that changed an object or a prefix is an inefficient task. The commits are chained to one another and the server must diff every commit in the log with its parent to check for the object/prefix version change. Every diff requires at least 4 object-store fetches and 4 sstables metadata (2 metaranges & 2 ranges) lookups. The Pyramid cache (The sstables cache) saves a lot of the object-store roundtrips. 
The client may request for more commits than are available for the object, e.g. `amount=3` when the object was modified twice. For the lakeFS server to find all versions, it needs to search the entire commit tree, where the cache is no longer effective, making the request extremely slow.
For some cases, searching the entire commit log is irrelevant. For example, a month old data set in a year old repository. For such cases, the client may hint the server for the lookup period. The server will stop searching for changes in older commits.

**Design**
Add the following to `logCommits` API:
```
  - in: query
    name: lookback_period
    description: if set, return only the commits in the last lookback_period.
    example: P3M
    schema:
      type: string
      format: iso8601
```
