### ISSUE TITLE
Catalog exporters: customized catalog properties 

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#7180]
Using the catalog exporter hook yaml definition, add an option to override (or specify) table descriptor properties by providing configurable table and schema names.
* The configurable keys may include a placeholder for `commit_id` (additional placeholders will be discussed) that will be replaced with the executing hook's commit id.
* The format will be: `custom.<table_descriptor_name>.<property>`.

Example:
```yaml
---
name: unity_exporter
on:
  post-commit: null
hooks:
  - id: unity_export
    type: lua
    properties:
      script_path: lua-hooks/unity_export_hook.lua
      args:
        ...
        table_defs:
          - my_table.yaml
        custom:
          my_table.yaml:
           - name: another_name_{commit_id}
        databricks_host: ...
        databricks_token: ...
        warehouse_id: ...
        catalog: ...
```
