### ISSUE TITLE
Support Dependencies in Actions `hooks.if` conditionals

### ISSUE THREAD

**Issue by imaouhoubi** [treeverse/lakeFS#7706]
Problem: 

Currently in LakeFS actions, When setting up Action Hooks, the `hooks.if` conditions are global and there is no way to specify for example if a hook has a dependency of the success or failure of another hook.

Details: 

Consider this workflow:
- `create_table_hook`: main hook
- `trigger_gitlab_pipeline_hook`: should run if `create_table_hook` fails
- `send_notification_hook`: should run if `trigger_gitlab_pipeline_hook` fails

if we try to implement this currently in lakefs actions, we would have something like this:

```yaml
- id: create_table_hook
  type: lua
- id: trigger_gitlab_pipeline_hook
  type: lua
  if: failure()
- id: send_notification_hook
  type: lua
  if: failure()
```

the issue we will have here is that the hooks `trigger_gitlab_pipeline_hook` and `send_notification_hook` will both be executed if `create_table_hook` fails.

instead, it would be more flexible if we could specify which hooks to listen in the `hooks.if` clause. 
here's the previous example with this proposal:

```yaml
- id: create_table_hook
  type: lua
- id: trigger_gitlab_pipeline_hook
  type: lua
  if: failure(create_table_hook)
- id: send_notification_hook
  type: lua
  if: failure(trigger_gitlab_pipeline_hook)
```

Note that in another case, we might want to specify multiple hooks to listen to for failure. In this case, if one of the hooks mentioned fails, it should execute the conditional hook. but if it's success, all the hooks mentioned should succeed before running the conditional hook.
