### ISSUE TITLE
Lua "Delta export example for Azure Blob Storage" example in docs has blank fields

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#7709]
There are several lines like
```yaml
          storage_account: "{{ .AzureStorageAccount }}"
```

But on https://docs.lakefs.io/howto/hooks/lua.html they are rendered as though Moustache tried to format them... and failed:
```yaml
      args:
        azure:
          storage_account: ""
          access_key: ""
```

Screenshot:
![screenshot of Lua docs page showing blank "storage_account" and "access_key" fields](https://github.com/treeverse/lakeFS/assets/7802932/979df987-2bb8-4672-896e-8e494ca2bd19)

Find a way to display this correctly to users, or display something else.
