### ISSUE TITLE
[Bug]: Creating a user using the superuser command can end up in an unrecoverable state

### ISSUE THREAD

**Issue by yonipeleg33** [treeverse/lakeFS#8490]
### What happened?

Relevant setup: OSS (no rbac)

Running `lakefs superuser --user-name <something>` ends up in an error:
```
Failed to setup admin user: add credentials for admin: no credentials found for user (admin): not found
```

Now, the state is broken: The specified user exists, but have _no valid credentials_.
Running `lakefs superuser` again fails with this error, as it allows only one user:
```
Failed to setup admin user: create user - failed to create user (admin): already exists
```
And deleting the user using `lakectl auth users delete` also fails, because there are no valid credentials to provide to `lakectl`.

The only way out is to delete the kv db and re-run lakefs.

## Steps to Reproduce:
LakeFS Config:
```yaml
---
database:
  type: "local"
  local:
    path: /tmp/lakefs_database
auth:
  encrypt:
    secret_key: "not relevant"
   
blockstore:
  type: local 
  local:
    path: /home/yoni/lakefs-local/repos
```
lakectl config:
```yaml
credentials:
  access_key_id: ***
  secret_access_key: ***
server:
  endpoint_url: http://127.0.0.1:8000
```
1. Run `lakefs run` with the config provided above
2. Go to `http://localhost:8000/setup` and create access+secret keys
3. Save them into the lakectl config provided above
4. Run `lakectl auth users delete --id admin` with the config provided above
5. Shutdown the lakefs server
6. Run `lakefs superuser --user-name admin --access-key-id ***`, and provided the access key from step (2)

### Root cause

This is happening because:

1. We first create the user: https://github.com/treeverse/lakeFS/blob/f2c64828c57e2993a7dd6f9f877069aa2e4667d4/pkg/auth/setup/setup.go#L173
2. Then, we go to the `else` clause here, because an access key is provided: https://github.com/treeverse/lakeFS/blob/f2c64828c57e2993a7dd6f9f877069aa2e4667d4/pkg/auth/setup/setup.go#L198
3. Lastly, we assume the case of providing an access key without a secret key means the user wants to import an existing user from the previous auth service: https://github.com/treeverse/lakeFS/blob/f2c64828c57e2993a7dd6f9f877069aa2e4667d4/pkg/auth/basic_service.go#L239
   We try to search for existing credentials and fail --> creating the unrecoverable state, where there is only one user and it has no credentials.

The assumption [that providing only access key means import] isn't necessarily flawed, but it is a footgun; users can accidentally put themselves in a really bad situation.

### Solution suggestion
1. This operation should be atomic - create user + create credentials. If this operation fails, we should rollback the user creation as well.
2. Allowing at least 2 credentials per user can give the user a second chance at saving the situation. Of course, if the same reproduce procedure is done for both keys the user ends up in the same situation, but giving another change should help avoid completely unrecoverable situations.
   Allowing > 1 key pair also allows for implementing key rotation without downtime, which we might want to add sometime.
