### ISSUE TITLE
Extend Config object

### ISSUE THREAD

**Issue by itaigilo** [treeverse/lakeFS#8498]
Include `storage_id` and other relevant params.

**Comment by N-o-Z** [comment]
@itaigilo, can you please provide more details for this task?
Which config struct? Is this the lakeFS config?
What are the other relevant params?

**Comment by itaigilo** [comment]
> Which config struct? Is this the lakeFS config? What are the other relevant params?

@N-o-Z It's about adding the following optional fields to the `StorageConfig` which is returned by the `GET /config` API:
```
blockstore_id:
    type: string
blockstore_description:
    type: string
default_blockstore: 
    type: boolean
    default: false
blockstore_extras:
    type: object
    description: blockstore specific properties. e.g., Self-managed s3 compatible storages will include the storage endpoint
    additionalProperties:
      type: string
```
