### ISSUE TITLE
[Feature] Introduce `prepare_commit` Hook

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#8818]
## Overview
Implement a new experimental hook type `prepare_commit` that allows users to automate changes before a commit is finalized. This hook will execute before the `pre_commit` hook during the initial commit request phase.

## Motivation
Users need the ability to automatically update object metadata as part of their commit workflow without manual intervention. This is particularly useful for cases where metadata needs to be enriched or updated based on file contents or other conditions before the commit is finalized.

### Hook Execution Flow
- The `prepare_commit` hook runs before the `pre_commit` hook
- Changes made during this phase do not require a commit lock
- Hook failures will block the commit process
- The hook event will include the same information as other hooks, except commit parents (set later during branch update)

### Example Usage
```yaml
name: enrich user metadata
on:
  prepare-commit:
    branches: 
    - main
hooks:
  - id: metadata
    type: lua
    properties:
      script: |
        local lakefs = require("lakefs")
        local time = require("time")
        print("Update README.md with user metadata")
        code, resp = lakefs.update_object_user_metadata(action.repository_id, action.branch_id, "README.md", { user = "nopcoder", updated_at = time.format_iso(time.now()) })
        print(code, resp)
```

## Important Notes
- This feature will be marked as experimental until we gather more user feedback
- Changes performed during this hook are not atomic
- Users should be aware of potential concurrent modification risks
- The hook can modify object metadata for any files, not just those in the commit

## Documentation Requirements
- Clear documentation about execution timing
- Explanation of non-atomic nature and associated risks
- Mark feature as experimental in documentation
- Include example use cases and configurations
